### ISSUE TITLE
Attack values for Polar Hunter and Tropic Hunter are incorrect

### ISSUE THREAD

**Issue by Zalathar** [TrentWest7190/mhcalc-backbone#4]
The attack values for Polar Hunter and Tropic Hunter appear to have been taken from the [Attack Buff Stacking List](https://www.reddit.com/r/MonsterHunter/comments/4uqood/psa_attack_buff_stacking_list_for_mhgenerations/), which is [translated from a Japanese guide](http://yiankutku.com/?p=1121).

I don't know whether those values are correct for MHX, but they're definitely wrong for Generations, [because I tested Generations myself and got different results](https://www.reddit.com/r/MonsterHunter/comments/4xijde/mhgen_effects_of_the_coldblooded_polar_hunter_and/).

Based on my testing, the correct attack values are:
- Polar Hunter gives +15 attack in a cold area
- Tropic Hunter gives +15 attack in a hot area
- Polar Hunter plus a Cold Drink gives +5 attack in any area, which stacks with the cold area bonus

**Comment by TrentWest7190** [comment]
Alright, thank you for the information. I'll update accordingly!

**Comment by TrentWest7190** [comment]
Alright, the values have been updated, thanks for letting me know.
